importScripts(
  "worker_base.js",
  "worker_state.js",
  "worker_runtime.js",
  "worker_binding.js",
  "event_wake_state.js",
  "worker_event_wake.js",
  "worker_schedule.js",
  "worker_transport.js",
  "native_events.js",
  "worker_event_diagnostics.js",
  "worker_controls.js",
  "worker_delivery.js",
  "worker_conversations.js",
  "worker_lab_commands.js",
  "worker_events.js"
);
