importScripts(
  "worker_base.js",
  "worker_state.js",
  "worker_runtime.js",
  "worker_binding.js",
  "worker_schedule.js",
  "worker_transport.js",
  "worker_controls.js",
  "worker_transient_recovery.js",
  "worker_transient_events.js",
  "worker_delivery.js",
  "worker_assistant_errors.js",
  "worker_conversations.js",
  "worker_spawn.js",
  "worker_adoption.js",
  "worker_retirement.js",
  "worker_lab_commands.js",
  "worker_events.js"
);
